RDKTV-11877: timezone interface
rdkcentral/ThunderInterfaces pull request #122
Opened 2022-01-31 13:36 UTC by npoltorapavlo

Reason for change: ITimeZone interface for
get/set timezone (ex. in a file).
Test Procedure: Builds.
Risks: Low
Signed-off-by: Nikita Poltorapavlo <npoltorapavlo@productengine.com>

2022-02-01 15:17 UTC, pwielders commented on interfaces/ITimeZone.h
> +  virtual string GetTimeZone() = 0;
I guess this can be a const method.

2022-02-02 11:32 UTC, mhughesacn requested changes
Sorry Nikita - pilot error here, never pressed <submit>

2022-02-02 12:06 UTC, pwielders approved these changes

2022-02-11 15:26 UTC, mhughesacn submitted a review, later dismissed

2022-02-11 15:26 UTC, mhughesacn commented
Thanks Nikita

2022-02-22 22:30 UTC, anand-ky commented
@pwielders - Pls help merge this PR.

2022-02-24 19:07 UTC, anand-ky commented
@npoltorapavlo - Pls bring this to R2 branch.

2022-02-24 19:47 UTC, npoltorapavlo commented
#128

2022-02-25 15:39 UTC, anand-ky commented
@mhughesacn - Confirming that we are good with these changes and can be brought to R2 branch.

2022-03-01 15:35 UTC, pwielders submitted a review, later dismissed

2022-03-02 11:41 UTC, pwielders approved these changes

2022-03-02 11:41 UTC, merged