[INITIAL] Adding JSONRPC interface for LogExport plugin
rdkcentral/ThunderInterfaces pull request #82
Opened 2021-08-25 09:58 UTC by Karthick-Somasundaresan

2021-08-30 07:08 UTC, pwielders requested changes

2021-08-30 07:08 UTC, pwielders commented on interfaces/ILogExport.h
> +        virtual uint32_t watch(const std::string& filename, const bool& fromBeginning ) = 0;
Please use PascalCase for consistency. Methods names are always following the PascalCase convention.

Please use consistent reference to the string type. Always use the string (.s.o. the std::string) See line 32, where you use string in the template and all others are std::string. Please move the later to string.

2021-08-30 07:09 UTC, pwielders commented on interfaces/ILogExport.h
> +        virtual ~ILogExport() {}
~ILogExport() overrider = default;

2021-09-02 12:16 UTC, MFransen69 commented
Hi Karthick, we discussed in person, let's close the PR for now

2021-09-02 12:16 UTC, closed without merging